package com.revature.dummymodels;

import com.revature.annotations.Column;
import com.revature.annotations.Entity;
import com.revature.annotations.Id;

@Entity(tableName="test_subtable")
public class SubTestClass {

	@Override
	public String toString() {
		return "SubTestClass [id=" + this.id + ", testUsername=" + this.name + "]";
	}

	@Id(columnName="subtest_id", autoGenerated = true)
	private int id;
	
	@Column(columnName="subtest_name", nullable = false, unique = false)
	private String name;

	public SubTestClass() {
		super();
	}

	public SubTestClass(final String name) {
		super();
		this.id = -1;
		this.name = name;
	}

	public SubTestClass(final int id, final String name) {
		super();
		this.id = id;
		this.name = name;
	}
	
	public int getId() {
		return this.id;
	}
	
	public String getTestUsername() {
		return this.name;
	}

	public void setTestUsername(final String name) {
		this.name = name;
	}
	
}
