package com.revature.dummymodels;

import com.revature.annotations.Column;
import com.revature.annotations.Entity;
import com.revature.annotations.Id;

@Entity(tableName="test_table")
public class Test {

	@Id(columnName="test_id", autoGenerated = true)
	private int id;
	
	@Column(columnName="test_username", nullable = false, unique = true)
	private String testUsername;
	
	@Column(columnName="test_password", nullable = false, unique = false)
	private String testPassword;
	
}
