package com.revature.models;

import java.util.Objects;

import com.revature.annotations.Column;
import com.revature.annotations.Entity;
import com.revature.annotations.Id;
import com.revature.util.ServletConfiguration;

@Entity(tableName="character_table")
public class Character {
	
	static {
		ServletConfiguration.addClass(Character.class);
	}
	
	@Id(autoGenerated = true, columnName = "character_id")
	private int id;
	
	@Column(columnName="name", nullable=false, unique = true)
	private String name;
	
	@Column(columnName="gender", nullable=false, unique = false)
	private String gender;
	
	@Column(columnName="race", nullable=false, unique = false)
	private String race;
	
	@Column(columnName="class", nullable=false, unique = false)
	private String clazz;

	@Column(columnName="specialAbility", nullable=false, unique = false)
	private String specialAbility;
	
	public Character() {
		super();
	}

	public Character(final String name, final String gender, final String race, final String clazz, final String specialAbility) {
		super();
		this.name = name;
		this.gender = gender;
		this.race = race;
		this.clazz = clazz;
		this.specialAbility = specialAbility;
	}

	public String getName() {
		return name;
	}

	public void setName(final String name) {
		this.name = name;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(final String gender) {
		this.gender = gender;
	}

	public String getRace() {
		return race;
	}

	public void setRace(final String race) {
		this.race = race;
	}

	public String getClazz() {
		return clazz;
	}

	public void setClazz(final String clazz) {
		this.clazz = clazz;
	}

	public String getSpecialAbility() {
		return specialAbility;
	}

	public void setSpecialAbility(final String specialAbility) {
		this.specialAbility = specialAbility;
	}

	@Override
	public String toString() {
		return "Character [name=" + name + ", gender=" + gender + ", race=" + race + ", clazz=" + clazz
				+ ", specialAbility=" + specialAbility + ", getName()=" + getName() + ", getGender()=" + getGender()
				+ ", getRace()=" + getRace() + ", getClazz()=" + getClazz() + ", getSpecialAbility()="
				+ getSpecialAbility() + ", getClass()=" + getClass() + ", hashCode()=" + hashCode() + ", toString()="
				+ super.toString() + "]";
	}

	@Override
	public int hashCode() {
		return Objects.hash(clazz, gender, name, race, specialAbility);
	}

	@Override
	public boolean equals(final Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final Character other = (Character) obj;
		return Objects.equals(clazz, other.clazz) && Objects.equals(gender, other.gender)
				&& Objects.equals(name, other.name) && Objects.equals(race, other.race)
				&& Objects.equals(specialAbility, other.specialAbility);
	}
	
}
