package com.revature.models;

import java.util.Objects;

import com.revature.annotations.Column;
import com.revature.annotations.Entity;
import com.revature.annotations.Id;

@Entity(tableName="character_statistics")
public class CharacterStats {
	
	@Id(autoGenerated = true, columnName = "id")
	private int id;

	@Column(columnName="characterLevel", nullable=false, unique = false)
	private int characterLevel;
	
	@Column(columnName="health", nullable=false, unique = false)
	private int health;
	
	@Column(columnName="mana", nullable=false, unique = false)
	private int mana;
	
	@Column(columnName="stamina", nullable=false, unique = false)
	private int stamina;
	
	@Column(columnName="speed", nullable=false, unique = false)
	private int speed;

	public CharacterStats() {
		super();
	}

	public CharacterStats(final int characterLevel, final int health, final int mana, final int stamina, final int speed) {
		super();
		this.id = -1;
		this.characterLevel = characterLevel;
		this.health = health;
		this.mana = mana;
		this.stamina = stamina;
		this.speed = speed;
	}

	public CharacterStats(final int id, final int characterLevel, final int health, final int mana, final int stamina, final int speed) {
		super();
		this.id = id;
		this.characterLevel = characterLevel;
		this.health = health;
		this.mana = mana;
		this.stamina = stamina;
		this.speed = speed;
	}

	public int getCharacterLevel() {
		return this.characterLevel;
	}

	public void setCharacterLevel(final int characterLevel) {
		this.characterLevel = characterLevel;
	}

	public int getHealth() {
		return this.health;
	}

	public void setHealth(final int health) {
		this.health = health;
	}

	public int getMana() {
		return this.mana;
	}

	public void setMana(final int mana) {
		this.mana = mana;
	}

	public int getStamina() {
		return this.stamina;
	}

	public void setStamina(final int stamina) {
		this.stamina = stamina;
	}

	public int getSpeed() {
		return this.speed;
	}

	public void setSpeed(final int speed) {
		this.speed = speed;
	}

	public int getId() {
		return this.id;
	}

	public void setId(final int id) {
		this.id = id;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.characterLevel, this.health, this.id, this.mana, this.speed, this.stamina);
	}

	@Override
	public boolean equals(final Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final CharacterStats other = (CharacterStats) obj;
		return this.characterLevel == other.characterLevel && this.health == other.health && this.id == other.id && this.mana == other.mana
				&& this.speed == other.speed && this.stamina == other.stamina;
	}

	@Override
	public String toString() {
		return "CharacterStats [id=" + this.id + ", characterLevel=" + this.characterLevel + ", health=" + this.health + ", mana="
				+ this.mana + ", stamina=" + this.stamina + ", speed=" + this.speed + "]";
	}	
	
}
