package com.revature.models;

import java.util.Objects;

import com.revature.annotations.Column;
import com.revature.annotations.Entity;
import com.revature.annotations.Id;

@Entity(tableName="character_table")
public class CharacterModel {
	
	@Id(autoGenerated = true, columnName = "character_id")
	private int id;
	
	@Column(columnName="username", nullable=false, unique = true)
	private String username;
	
	@Column(columnName="password", nullable=false, unique = false)
	private String password;
	
	@Column(columnName="gender", nullable=false, unique = false)
	private String gender;
	
	@Column(columnName="race", nullable=false, unique = false)
	private String race;
	
	@Column(columnName="class", nullable=false, unique = false)
	private String clazz;

	@Column(columnName="specialAbility", nullable=false, unique = false)
	private String specialAbility;
	
	public CharacterModel() {
		super();
	}

	public CharacterModel(final String username, final String password, final String gender, final String race, final String clazz, final String specialAbility) {
		super();
		this.username = username;
		this.password = password;
		this.gender = gender;
		this.race = race;
		this.clazz = clazz;
		this.specialAbility = specialAbility;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getRace() {
		return race;
	}

	public void setRace(String race) {
		this.race = race;
	}

	public String getClazz() {
		return clazz;
	}

	public void setClazz(String clazz) {
		this.clazz = clazz;
	}

	public String getSpecialAbility() {
		return specialAbility;
	}

	public void setSpecialAbility(String specialAbility) {
		this.specialAbility = specialAbility;
	}

	@Override
	public int hashCode() {
		return Objects.hash(clazz, gender, id, password, race, specialAbility, username);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CharacterModel other = (CharacterModel) obj;
		return Objects.equals(clazz, other.clazz) && Objects.equals(gender, other.gender) && id == other.id
				&& Objects.equals(password, other.password) && Objects.equals(race, other.race)
				&& Objects.equals(specialAbility, other.specialAbility) && Objects.equals(username, other.username);
	}

	@Override
	public String toString() {
		return "CharacterModel [id=" + id + ", username=" + username + ", password=" + password + ", gender=" + gender
				+ ", race=" + race + ", clazz=" + clazz + ", specialAbility=" + specialAbility + "]";
	}

	

}
